### ISSUE TITLE
Dub bug

### ISSUE THREAD

**Issue by MANKEYYENAME** [submada/btl#1]
The "unittest" configuration is built by default. Because of this, when exiting main, assert from btl is triggered
```
btl:autoptr 1.0.0-rc.4: target for configuration "unittest" is up to date.
btl:string 1.0.0-rc.4: target for configuration "unittest" is up to date. 
btl:vector 1.0.0-rc.4: target for configuration "unittest" is up to date 
```

**Comment by submada** [comment]
I add new default(empty) configuration for all packages.

The triggered asserts from btl unittest configuration trigger when some memory is not freed. It can happend when string/smart_ptr/vector is inside gc allocated array (dlang bug for copy ctors), for value sequence on the stack (dlang bug for dtors) or some other bug. Can you create some example when this assert trigger in your code?

**Comment by MANKEYYENAME** [comment]
Thanks, I have a global associative array with weak pointers in my code. It will have to be forcibly removed.
